//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ReferenciaNegocio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pais", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class Pais : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idpaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombrePaisField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idpais {
            get {
                return this.idpaisField;
            }
            set {
                if ((object.ReferenceEquals(this.idpaisField, value) != true)) {
                    this.idpaisField = value;
                    this.RaisePropertyChanged("idpais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombrePais {
            get {
                return this.nombrePaisField;
            }
            set {
                if ((object.ReferenceEquals(this.nombrePaisField, value) != true)) {
                    this.nombrePaisField = value;
                    this.RaisePropertyChanged("nombrePais");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string direccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idclienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idpaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.direccionField, value) != true)) {
                    this.direccionField = value;
                    this.RaisePropertyChanged("direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idcliente {
            get {
                return this.idclienteField;
            }
            set {
                if ((object.ReferenceEquals(this.idclienteField, value) != true)) {
                    this.idclienteField = value;
                    this.RaisePropertyChanged("idcliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idpais {
            get {
                return this.idpaisField;
            }
            set {
                if ((object.ReferenceEquals(this.idpaisField, value) != true)) {
                    this.idpaisField = value;
                    this.RaisePropertyChanged("idpais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoField, value) != true)) {
                    this.telefonoField = value;
                    this.RaisePropertyChanged("telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReferenciaNegocio.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListadoPais", ReplyAction="http://tempuri.org/IService1/ListadoPaisResponse")]
        WebApplication1.ReferenciaNegocio.Pais[] ListadoPais();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListadoPais", ReplyAction="http://tempuri.org/IService1/ListadoPaisResponse")]
        System.Threading.Tasks.Task<WebApplication1.ReferenciaNegocio.Pais[]> ListadoPaisAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListadoCliente", ReplyAction="http://tempuri.org/IService1/ListadoClienteResponse")]
        WebApplication1.ReferenciaNegocio.Cliente[] ListadoCliente();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListadoCliente", ReplyAction="http://tempuri.org/IService1/ListadoClienteResponse")]
        System.Threading.Tasks.Task<WebApplication1.ReferenciaNegocio.Cliente[]> ListadoClienteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AgregarCliente", ReplyAction="http://tempuri.org/IService1/AgregarClienteResponse")]
        string AgregarCliente(WebApplication1.ReferenciaNegocio.Cliente reg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AgregarCliente", ReplyAction="http://tempuri.org/IService1/AgregarClienteResponse")]
        System.Threading.Tasks.Task<string> AgregarClienteAsync(WebApplication1.ReferenciaNegocio.Cliente reg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarCliente", ReplyAction="http://tempuri.org/IService1/ActualizarClienteResponse")]
        string ActualizarCliente(WebApplication1.ReferenciaNegocio.Cliente reg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarCliente", ReplyAction="http://tempuri.org/IService1/ActualizarClienteResponse")]
        System.Threading.Tasks.Task<string> ActualizarClienteAsync(WebApplication1.ReferenciaNegocio.Cliente reg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarCliente", ReplyAction="http://tempuri.org/IService1/EliminarClienteResponse")]
        string EliminarCliente(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarCliente", ReplyAction="http://tempuri.org/IService1/EliminarClienteResponse")]
        System.Threading.Tasks.Task<string> EliminarClienteAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebApplication1.ReferenciaNegocio.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebApplication1.ReferenciaNegocio.IService1>, WebApplication1.ReferenciaNegocio.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebApplication1.ReferenciaNegocio.Pais[] ListadoPais() {
            return base.Channel.ListadoPais();
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ReferenciaNegocio.Pais[]> ListadoPaisAsync() {
            return base.Channel.ListadoPaisAsync();
        }
        
        public WebApplication1.ReferenciaNegocio.Cliente[] ListadoCliente() {
            return base.Channel.ListadoCliente();
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ReferenciaNegocio.Cliente[]> ListadoClienteAsync() {
            return base.Channel.ListadoClienteAsync();
        }
        
        public string AgregarCliente(WebApplication1.ReferenciaNegocio.Cliente reg) {
            return base.Channel.AgregarCliente(reg);
        }
        
        public System.Threading.Tasks.Task<string> AgregarClienteAsync(WebApplication1.ReferenciaNegocio.Cliente reg) {
            return base.Channel.AgregarClienteAsync(reg);
        }
        
        public string ActualizarCliente(WebApplication1.ReferenciaNegocio.Cliente reg) {
            return base.Channel.ActualizarCliente(reg);
        }
        
        public System.Threading.Tasks.Task<string> ActualizarClienteAsync(WebApplication1.ReferenciaNegocio.Cliente reg) {
            return base.Channel.ActualizarClienteAsync(reg);
        }
        
        public string EliminarCliente(string id) {
            return base.Channel.EliminarCliente(id);
        }
        
        public System.Threading.Tasks.Task<string> EliminarClienteAsync(string id) {
            return base.Channel.EliminarClienteAsync(id);
        }
    }
}
